"""Konstanten für Grocery Icon Map."""

DOMAIN = "grocery_icon_map"
CONF_MAPPINGS = "mappings"
CONF_LABEL = "label"
CONF_ICON = "icon"
CONF_CATEGORY = "category"
CONF_ICON_STYLE = "icon_style"

STYLE_EMOJI = "emoji"
STYLE_MDI = "mdi"
DEFAULT_ICON_STYLE = STYLE_EMOJI
DEFAULT_CATEGORY = "Sonstiges"

DEFAULT_ICON_BY_STYLE = {
    STYLE_EMOJI: "🛒",
    STYLE_MDI: "mdi:cart-outline",
}

# Vorschlag beim ersten Einrichten, je nach gewähltem Icon-Stil. Rein als
# Startpunkt gedacht - über den Optionen-Dialog frei editierbar, erweiterbar
# und entfernbar. Jeder Eintrag hat ein Icon (mdi:... oder Emoji-Zeichen) und
# eine Kategorie (für die Gruppen-Ansicht der Karte).
DEFAULT_MAPPINGS_BY_STYLE: dict[str, dict[str, dict[str, str]]] = {
    STYLE_EMOJI: {
        "Milch": {"icon": "🥛", "category": "Milchprodukte"},
        "Butter": {"icon": "🧈", "category": "Milchprodukte"},
        "Joghurt": {"icon": "🥣", "category": "Milchprodukte"},
        "Quark": {"icon": "🥣", "category": "Milchprodukte"},
        "Sahne": {"icon": "🥛", "category": "Milchprodukte"},
        "Käse": {"icon": "🧀", "category": "Milchprodukte"},
        "Ei": {"icon": "🥚", "category": "Milchprodukte"},
        "Brot": {"icon": "🍞", "category": "Backwaren"},
        "Croissant": {"icon": "🥐", "category": "Backwaren"},
        "Mehl": {"icon": "🌾", "category": "Backwaren"},
        "Apfel": {"icon": "🍎", "category": "Obst"},
        "Birne": {"icon": "🍐", "category": "Obst"},
        "Banane": {"icon": "🍌", "category": "Obst"},
        "Traube": {"icon": "🍇", "category": "Obst"},
        "Kirsche": {"icon": "🍒", "category": "Obst"},
        "Zitrone": {"icon": "🍋", "category": "Obst"},
        "Orange": {"icon": "🍊", "category": "Obst"},
        "Wassermelone": {"icon": "🍉", "category": "Obst"},
        "Ananas": {"icon": "🍍", "category": "Obst"},
        "Avocado": {"icon": "🥑", "category": "Obst"},
        "Kartoffel": {"icon": "🥔", "category": "Gemüse"},
        "Karotte": {"icon": "🥕", "category": "Gemüse"},
        "Zwiebel": {"icon": "🧅", "category": "Gemüse"},
        "Knoblauch": {"icon": "🧄", "category": "Gemüse"},
        "Tomate": {"icon": "🍅", "category": "Gemüse"},
        "Salat": {"icon": "🥬", "category": "Gemüse"},
        "Paprika": {"icon": "🫑", "category": "Gemüse"},
        "Gurke": {"icon": "🥒", "category": "Gemüse"},
        "Pilz": {"icon": "🍄", "category": "Gemüse"},
        "Hähnchen": {"icon": "🍗", "category": "Fleisch & Wurst"},
        "Hackfleisch": {"icon": "🥩", "category": "Fleisch & Wurst"},
        "Wurst": {"icon": "🌭", "category": "Fleisch & Wurst"},
        "Fisch": {"icon": "🐟", "category": "Fisch"},
        "Wasser": {"icon": "💧", "category": "Getränke"},
        "Saft": {"icon": "🧃", "category": "Getränke"},
        "Kaffee": {"icon": "☕", "category": "Getränke"},
        "Tee": {"icon": "🍵", "category": "Getränke"},
        "Bier": {"icon": "🍺", "category": "Getränke"},
        "Wein": {"icon": "🍷", "category": "Getränke"},
        "Nudel": {"icon": "🍝", "category": "Trockenwaren & Konserven"},
        "Reis": {"icon": "🍚", "category": "Trockenwaren & Konserven"},
        "Müsli": {"icon": "🥣", "category": "Trockenwaren & Konserven"},
        "Zucker": {"icon": "🧊", "category": "Gewürze & Öle"},
        "Salz": {"icon": "🧂", "category": "Gewürze & Öle"},
        "Öl": {"icon": "🫒", "category": "Gewürze & Öle"},
        "Schokolade": {"icon": "🍫", "category": "Süßes & Snacks"},
        "Keks": {"icon": "🍪", "category": "Süßes & Snacks"},
        "Kuchen": {"icon": "🍰", "category": "Süßes & Snacks"},
        "Eis": {"icon": "🍨", "category": "Süßes & Snacks"},
        "Marmelade": {"icon": "🍯", "category": "Süßes & Snacks"},
        "Tierfutter": {"icon": "🐾", "category": "Tierbedarf"},
        "Toilettenpapier": {"icon": "🧻", "category": "Drogerie & Hygiene"},
        "Zahnpasta": {"icon": "🪥", "category": "Drogerie & Hygiene"},
        "Spülmittel": {"icon": "🧽", "category": "Reinigung & Haushalt"},
        "Waschmittel": {"icon": "🧴", "category": "Reinigung & Haushalt"},
    },
    STYLE_MDI: {
        "Milch": {"icon": "mdi:cup", "category": "Milchprodukte"},
        "Butter": {"icon": "mdi:food-variant", "category": "Milchprodukte"},
        "Joghurt": {"icon": "mdi:bowl-mix", "category": "Milchprodukte"},
        "Quark": {"icon": "mdi:bowl-mix", "category": "Milchprodukte"},
        "Sahne": {"icon": "mdi:cup-outline", "category": "Milchprodukte"},
        "Käse": {"icon": "mdi:cheese", "category": "Milchprodukte"},
        "Ei": {"icon": "mdi:egg", "category": "Milchprodukte"},
        "Brot": {"icon": "mdi:bread-slice", "category": "Backwaren"},
        "Croissant": {"icon": "mdi:food-croissant", "category": "Backwaren"},
        "Mehl": {"icon": "mdi:barley", "category": "Backwaren"},
        "Apfel": {"icon": "mdi:food-apple", "category": "Obst"},
        "Birne": {"icon": "mdi:fruit-pear", "category": "Obst"},
        "Banane": {"icon": "mdi:food-apple-outline", "category": "Obst"},
        "Traube": {"icon": "mdi:fruit-grapes", "category": "Obst"},
        "Kirsche": {"icon": "mdi:fruit-cherries", "category": "Obst"},
        "Zitrone": {"icon": "mdi:fruit-citrus", "category": "Obst"},
        "Orange": {"icon": "mdi:fruit-citrus", "category": "Obst"},
        "Wassermelone": {"icon": "mdi:fruit-watermelon", "category": "Obst"},
        "Ananas": {"icon": "mdi:fruit-pineapple", "category": "Obst"},
        "Avocado": {"icon": "mdi:food-apple-outline", "category": "Obst"},
        "Kartoffel": {"icon": "mdi:sack-outline", "category": "Gemüse"},
        "Karotte": {"icon": "mdi:carrot", "category": "Gemüse"},
        "Zwiebel": {"icon": "mdi:circle-outline", "category": "Gemüse"},
        "Knoblauch": {"icon": "mdi:circle-outline", "category": "Gemüse"},
        "Tomate": {"icon": "mdi:fruit-watermelon", "category": "Gemüse"},
        "Salat": {"icon": "mdi:food-apple-outline", "category": "Gemüse"},
        "Paprika": {"icon": "mdi:chili-mild", "category": "Gemüse"},
        "Gurke": {"icon": "mdi:food-apple-outline", "category": "Gemüse"},
        "Pilz": {"icon": "mdi:mushroom", "category": "Gemüse"},
        "Hähnchen": {"icon": "mdi:food-drumstick", "category": "Fleisch & Wurst"},
        "Hackfleisch": {"icon": "mdi:food-steak", "category": "Fleisch & Wurst"},
        "Wurst": {"icon": "mdi:sausage", "category": "Fleisch & Wurst"},
        "Fisch": {"icon": "mdi:fish", "category": "Fisch"},
        "Wasser": {"icon": "mdi:cup-water", "category": "Getränke"},
        "Saft": {"icon": "mdi:cup", "category": "Getränke"},
        "Kaffee": {"icon": "mdi:coffee", "category": "Getränke"},
        "Tee": {"icon": "mdi:tea", "category": "Getränke"},
        "Bier": {"icon": "mdi:beer", "category": "Getränke"},
        "Wein": {"icon": "mdi:bottle-wine", "category": "Getränke"},
        "Nudel": {"icon": "mdi:pasta", "category": "Trockenwaren & Konserven"},
        "Reis": {"icon": "mdi:rice", "category": "Trockenwaren & Konserven"},
        "Müsli": {"icon": "mdi:bowl-mix", "category": "Trockenwaren & Konserven"},
        "Zucker": {"icon": "mdi:cube-outline", "category": "Gewürze & Öle"},
        "Salz": {"icon": "mdi:shaker-outline", "category": "Gewürze & Öle"},
        "Öl": {"icon": "mdi:oil", "category": "Gewürze & Öle"},
        "Schokolade": {"icon": "mdi:candy-outline", "category": "Süßes & Snacks"},
        "Keks": {"icon": "mdi:cookie", "category": "Süßes & Snacks"},
        "Kuchen": {"icon": "mdi:cupcake", "category": "Süßes & Snacks"},
        "Eis": {"icon": "mdi:ice-cream", "category": "Süßes & Snacks"},
        "Marmelade": {"icon": "mdi:beehive-outline", "category": "Süßes & Snacks"},
        "Tierfutter": {"icon": "mdi:dog-side", "category": "Tierbedarf"},
        "Toilettenpapier": {"icon": "mdi:paper-roll", "category": "Drogerie & Hygiene"},
        "Zahnpasta": {"icon": "mdi:tooth", "category": "Drogerie & Hygiene"},
        "Spülmittel": {"icon": "mdi:spray-bottle", "category": "Reinigung & Haushalt"},
        "Waschmittel": {"icon": "mdi:washing-machine", "category": "Reinigung & Haushalt"},
    },
}
